// Client
export { TeardropClient } from "./client";
export type { TeardropClientOptions } from "./client";

// Resource modules
export { AuthModule } from "./auth";
export { AgentModule } from "./agent";
export type { AgentRunOptions } from "./agent";
export { SchedulesModule } from "./schedules";
export { EventTriggersModule } from "./eventTriggers";
export { CredentialsModule } from "./credentials";
export { ToolsModule } from "./tools";
export { McpModule } from "./mcp";
export { MemoryModule } from "./memory";
export { WalletsModule } from "./wallets";
export { AgentWalletsModule } from "./agentWallets";
export { BillingModule } from "./billing";
export { UsageModule } from "./usage";
export { MarketplaceModule } from "./marketplace";
export { LlmModule } from "./llmConfig";
export { ModelsModule } from "./models";
export { A2AModule } from "./a2a";
export { AdminModule } from "./admin";

// Transport (TokenManager exported for advanced use)
export { TokenManager } from "./transport";

// Errors
export {
  TeardropError,
  TeardropApiError,
  AuthenticationError,
  PaymentRequiredError,
  ForbiddenError,
  NotFoundError,
  ConflictError,
  ValidationError,
  RateLimitError,
  GatewayError,
} from "./errors";

// Types
export type {
  TokenResponse,
  JwtPayloadBase,
  JwtPayloadSiwe,
  MeResponse,
  AgentRunRequest,
  AgentTool,
  AgentToolsResponse,
  ToolPolicy,
  Page,
  SseEvent,
  RunStartedEvent,
  TextMessageStartEvent,
  TextMessageContentEvent,
  TextMessageEndEvent,
  ToolCallStartEvent,
  ToolCallEndEvent,
  CustomToolOutputEvent,
  SurfaceUpdateEvent,
  UsageSummaryEvent,
  BillingSettlementEvent,
  RunFinishedEvent,
  ErrorEvent,
  DoneEvent,
  CreateScheduledRunRequest,
  UpdateScheduledRunRequest,
  ScheduledRun,
  ScheduledRunResult,
  CreateEventTriggerRequest,
  UpdateEventTriggerRequest,
  EventTrigger,
  EventTriggerWithSecret,
  RotateEventTriggerSecretResponse,
  EventDispatchAccepted,
  OrgCredentialsEntry,
  OrgCredentialsResponse,
  RegenerateCredentialsResponse,
  OrgTool,
  CreateOrgToolRequest,
  UpdateOrgToolRequest,
  McpServerAuthType,
  OrgMcpServer,
  CreateMcpServerRequest,
  UpdateMcpServerRequest,
  McpToolDefinition,
  DiscoverMcpToolsResponse,
  MemoryEntry,
  StoreMemoryRequest,
  Wallet,
  LinkWalletRequest,
  ToolPricing,
  BillingPricingResponse,
  CreditBalance,
  BillingHistoryEntry,
  Invoice,
  InvoiceListResponse,
  CreditHistoryEntry,
  CreditHistoryResponse,
  StripeTopupRequest,
  StripeTopupResponse,
  StripeTopupStatusResponse,
  UsdcTopupRequirements,
  UsdcTopupRequest,
  UsageSummary,
  MarketplaceTool,
  AuthorConfig,
  EarningsEntry,
  WithdrawRequest,
  MarketplaceSubscription,
  // New spec types
  AuthMeResponse,
  SiweNonceResponse,
  VerifyEmailResponse,
  ResendVerificationRequest,
  ResendVerificationResponse,
  CreateInviteRequest,
  CreateInviteResponse,
  AgentDecisionRecord,
  AgentDecisionListResponse,
  RunOutcomeRating,
  RunOutcomeRequest,
  RunOutcomeResponse,
  ToolExclusionRequest,
  ToolExclusionActionResponse,
  ToolExclusionListResponse,
  ToolExclusionRemovedResponse,
  OrgCreateA2AAgentRequest,
  OrgA2AAgentResponse,
  OrgA2AAgentListItem,
  OrgA2AAgentDeletedResponse,
  A2ADelegationEvent,
  ScheduledRunItem,
  ScheduledRunListResponse,
  ScheduleDeletedResponse,
  ScheduledRunResultItem,
  ScheduledRunResultsResponse,
  EventTriggerItem,
  EventTriggerCreatedResponse,
  EventTriggerListResponse,
  EventDispatchResponse,
  MemoryListItem,
  MemoryCreatedResponse,
  MemoryDeletedResponse,
  WalletItem,
  WalletDeletedResponse,
  AgentWalletResponse,
  AgentWalletDeactivatedResponse,
  OrgCredentialItem,
  OrgCredentialRegenerateResponse,
  BillingBalanceResponse,
  BillingHistoryItem,
  StripeTopupSessionResponse,
  StripeSessionStatusResponse,
  UsdcTopupRequirementsResponse,
  UsdcTopupResponse,
  MarketplaceToolSummary,
  MarketplaceCatalogResponse,
  MarketplaceAuthorProfileResponse,
  MarketplaceCatalogDetailResponse,
  MarketplaceAuthorConfigResponse,
  MarketplaceBalanceResponse,
  MarketplaceEarningEntry,
  MarketplaceEarningsResponse,
  MarketplaceEarningsByToolEntry,
  MarketplaceEarningsByToolResponse,
  MarketplaceImportPreviewRequest,
  MarketplaceImportPreviewError,
  ImportPreviewSchemaStatus,
  ImportPreviewDroppedFeatures,
  MarketplaceImportPreviewTool,
  MarketplaceImportPreviewResponse,
  MarketplaceToolCategory,
  MarketplaceImportPublishToolRequest,
  MarketplaceImportPublishRequest,
  MarketplaceImportPublishedTool,
  MarketplaceImportPublishCreatedItem,
  MarketplaceImportPublishError,
  MarketplaceImportPublishResponse,
  RunFeedbackRequest,
  RunFeedbackResponse,
  MarketplaceWithdrawalResponse,
  MarketplaceWithdrawalHistoryItem,
  MarketplaceWithdrawalsListResponse,
  MarketplaceSubscriptionItem,
  MarketplaceSubscriptionResponse,
  MarketplaceSubscriptionListResponse,
  UnsubscribeResponse,
  LlmConfigDeletedResponse,
  LlmConfigResponse,
  McpServerResponse,
  McpServerDeletedResponse,
  McpDiscoverResponse,
  TestMcpToolRequest,
  TestMcpToolResponse,
  OrgToolResponse,
  ToolDeletedResponse,
  SubscriptionsResponse,
  ProviderType,
  RoutingPreference,
  OrgLlmConfig,
  SetLlmConfigRequest,
  ModelPricing,
  ModelRunBenchmarks,
  ModelInfo,
  ModelBenchmarksResponse,
  AddTrustedAgentRequest,
  TrustedAgent,
  AgentWallet,
  AgentCard,
  HealthResponse,
  TestWebhookRequest,
  TestWebhookResponse,
  // Backward-compat aliases
  BillingBalance,
  PricingInfo,
  CreateCustomToolRequest,
  CustomTool,
  CreateOrgRequest,
  CreateOrgResponse,
  CreateUserRequest,
  CreateUserResponse,
  CreateClientCredentialsRequest,
  CreateClientCredentialsResponse,
  OrgSpendingConfigResponse,
  SpendingConfigUpdate,
  ToolPricingOverrideRequest,
  ToolPricingOverrideResponse,
  ToolPricingDeleteResponse,
  TopupRequest,
  AdminTopupResponse,
  AdminCreateA2AAgentRequest,
  AdminA2AAgentResponse,
  AdminA2AAgentListItem,
  AdminA2AAgentDeletedResponse,
  PendingSettlementItem,
  PendingSettlementsResponse,
  SettlementRetryResponse,
  RevenueSummaryResponse,
  AdminWithdrawalItem,
  AdminWithdrawalListResponse,
  AdminWithdrawalActionResponse,
  CompleteWithdrawalRequest,
  CompleteWithdrawalResponse,
  WithdrawalResetResponse,
  SettlementBalanceResponse,
  MarketplaceSweepResponse,
  SweepStatusItem,
  SweepStatusResponse,
  AdminMemoryItem,
  AdminMemoryListResponse,
  AdminMemoryPurgeResponse,
} from "./types";

// Constants
export {
  MODELS_BY_PROVIDER,
  EVENT_CUSTOM,
  EVENT_RUN_STARTED,
  EVENT_RUN_FINISHED,
  EVENT_TEXT_MSG_START,
  EVENT_TEXT_MSG_CONTENT,
  EVENT_TEXT_MSG_END,
  EVENT_TOOL_CALL_START,
  EVENT_TOOL_CALL_END,
  EVENT_SURFACE_UPDATE,
  EVENT_USAGE_SUMMARY,
  EVENT_BILLING_SETTLEMENT,
  EVENT_ERROR,
  EVENT_DONE,
} from "./types";

// Utilities
export { parseSseStream, collectText, collectTextSync } from "./utils/parseSseStream";
export { parseMcpToolName } from "./utils/parseMcpToolName";
export { parseMarketplaceToolName } from "./utils/parseMarketplaceToolName";
export { formatUsdc, parseUsdc } from "./utils/atomicUsdc";
